const companyRoutes = require('./companies.route');
const rolesRoutes = require('./roles.route');
const usersRoutes = require('./users.route');
const countryRoutes = require('./countries.route');
const sectorRoutes = require('./sectors.route');
const employee_strengthRoute = require('./employee_strength.route');
const avrageempRoute = require('./average_employee.route');
const feedbackfreqRoute = require('./feedback_frequencies.route');
const packagesRoute = require('./package.route');
const couponsRoute = require('./coupons.route');
const questionRoute = require('./questions.route');
const optionRoute = require('./options.route');
const managersRoute = require('./managers.route');
const generalmanagersRoute = require('./general_managers.route');
const EmployeeRoute = require('./employee.route');
const Collect_feeedbackRoute = require('./collect_feedback.route');
const Year_Of_Experience = require('./year_of_experience.route');
const checktest = require('./checktest.route');
const question_option_mapping = require('./question_option_mapping.route');
const surveys = require('./surveys.route');
const survey_analysis = require('./survey_analysis.route');
const survey_user_mapping = require('./survey_user_mapping.route');
const survey_answers = require('./survey_answers.route');

module.exports = (router) => {
    companyRoutes(router);
    rolesRoutes(router);
    usersRoutes(router);
    countryRoutes(router);
    sectorRoutes(router);
    employee_strengthRoute(router);
    avrageempRoute(router);
    feedbackfreqRoute(router);
    packagesRoute(router);
    couponsRoute(router);
    questionRoute(router);
    optionRoute(router);
    managersRoute(router);
    generalmanagersRoute(router);
    EmployeeRoute(router);
    Collect_feeedbackRoute(router);
    Year_Of_Experience(router);
    checktest(router);
    question_option_mapping(router);
    survey_analysis(router);
    survey_user_mapping(router);
    survey_answers(router);

    return router;
};
